"""  migration

Revision ID: 7d0a0fb4d9b2
Revises: ff53bc5745cb
Create Date: 2018-09-20 11:53:27.373287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0a0fb4d9b2'
down_revision = 'ff53bc5745cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'link')
    # ### end Alembic commands ###
