"""comments

Revision ID: 983b223ccd76
Revises: d749a82df70d
Create Date: 2018-09-20 14:28:11.661575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983b223ccd76'
down_revision = 'd749a82df70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('projects_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_userid_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_postid_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'projects', ['projects_id'], ['id'])
    op.drop_column('comments', 'text')
    op.drop_column('comments', 'userid')
    op.drop_column('comments', 'postid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('postid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_postid_fkey', 'comments', 'projects', ['postid'], ['id'])
    op.create_foreign_key('comments_userid_fkey', 'comments', 'users', ['userid'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'projects_id')
    op.drop_column('comments', 'details')
    # ### end Alembic commands ###
